/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ifpb.dac.ga.desktop.ui;

import edu.ifpb.dac.ga.entidades.entidades.Administrador;

/**
 *
 * @author Marcelo Augusto
 */
public class FramePrincipalAdmin extends javax.swing.JFrame {
    private Login login;
    private Administrador administrador;
    /**
     * Creates new form Administracao
     */

    public FramePrincipalAdmin() {
        initComponents();
        setContentPane(new PainelPrincipal());
        setLocationRelativeTo(null); 
    }

    FramePrincipalAdmin(Login aThis, Administrador administrador) {
        this.administrador = administrador;
        this.login = aThis;
        initComponents();
        setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        CadastroAlunoMenuItem = new javax.swing.JMenuItem();
        listarAlunoMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        CadastroProfessorMenuItem = new javax.swing.JMenuItem();
        listarProfessorMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        CadastroAdministradorMenuItem = new javax.swing.JMenuItem();
        ListarAdministradorMenuItem = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        CadastroCursoMenuItem = new javax.swing.JMenuItem();
        listarCursoMenuItem = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        CadastroDisciplinaMenuItem = new javax.swing.JMenuItem();
        listarDisciplinaMenuItem = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        CadastroTurmaMenuItem = new javax.swing.JMenuItem();
        listarTurmaMenuItem = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem38 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(910, 680));
        getContentPane().setLayout(null);

        jMenu9.setText("Arquivo");

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem1);

        jMenuBar1.add(jMenu9);

        jMenu1.setText("Aluno");

        CadastroAlunoMenuItem.setText("Cadastrar");
        CadastroAlunoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroAlunoMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(CadastroAlunoMenuItem);

        listarAlunoMenuItem.setText("Gerenciar");
        listarAlunoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarAlunoMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(listarAlunoMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Professor");

        CadastroProfessorMenuItem.setText("Cadastrar");
        CadastroProfessorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroProfessorMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(CadastroProfessorMenuItem);

        listarProfessorMenuItem.setText("Gerenciar");
        listarProfessorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarProfessorMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(listarProfessorMenuItem);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Administrador");

        CadastroAdministradorMenuItem.setText("Cadastrar");
        CadastroAdministradorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroAdministradorMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(CadastroAdministradorMenuItem);

        ListarAdministradorMenuItem.setText("Gerenciar");
        ListarAdministradorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarAdministradorMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(ListarAdministradorMenuItem);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Curso");

        CadastroCursoMenuItem.setText("Cadastrar");
        CadastroCursoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroCursoMenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(CadastroCursoMenuItem);

        listarCursoMenuItem.setText("Gerenciar");
        listarCursoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarCursoMenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(listarCursoMenuItem);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Disciplina");

        CadastroDisciplinaMenuItem.setText("Cadastrar");
        CadastroDisciplinaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroDisciplinaMenuItemActionPerformed(evt);
            }
        });
        jMenu5.add(CadastroDisciplinaMenuItem);

        listarDisciplinaMenuItem.setText("Gerenciar");
        listarDisciplinaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarDisciplinaMenuItemActionPerformed(evt);
            }
        });
        jMenu5.add(listarDisciplinaMenuItem);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Turma");

        CadastroTurmaMenuItem.setText("Cadastrar nova turma");
        CadastroTurmaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroTurmaMenuItemActionPerformed(evt);
            }
        });
        jMenu6.add(CadastroTurmaMenuItem);

        listarTurmaMenuItem.setText("Gerenciar turmas cadastradas");
        listarTurmaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarTurmaMenuItemActionPerformed(evt);
            }
        });
        jMenu6.add(listarTurmaMenuItem);

        jMenuItem7.setText("Cadastrar horário de turma");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem7);

        jMenuBar1.add(jMenu6);

        jMenu10.setText("Aula");

        jMenuItem5.setText("Cadastrar reposição de aula");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem5);

        jMenuBar1.add(jMenu10);

        jMenu7.setText("Locais de aula");

        jMenuItem38.setText("Listar");
        jMenuItem38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem38ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem38);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listarAlunoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarAlunoMenuItemActionPerformed
        this.setContentPane(new ListarAlunosPainel(this));
        setVisible(true);
    }//GEN-LAST:event_listarAlunoMenuItemActionPerformed

    private void listarProfessorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarProfessorMenuItemActionPerformed
        this.setContentPane(new ListarProfesoresPainel(this));
        setVisible(true);
    }//GEN-LAST:event_listarProfessorMenuItemActionPerformed

    private void ListarAdministradorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarAdministradorMenuItemActionPerformed
        this.setContentPane(new ListarAdministradoresPainel(this));
        setVisible(true);
    }//GEN-LAST:event_ListarAdministradorMenuItemActionPerformed

    private void listarCursoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarCursoMenuItemActionPerformed
        this.setContentPane(new ListarCursosPainel(this));
        setVisible(true);
    }//GEN-LAST:event_listarCursoMenuItemActionPerformed

    private void listarDisciplinaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarDisciplinaMenuItemActionPerformed
        this.setContentPane(new ListarDisciplinasPainel(this));
        setVisible(true);
    }//GEN-LAST:event_listarDisciplinaMenuItemActionPerformed

    private void listarTurmaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarTurmaMenuItemActionPerformed
        this.setContentPane(new ListarTurmasPainel(this));
        setVisible(true);
    }//GEN-LAST:event_listarTurmaMenuItemActionPerformed

    private void CadastroAlunoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroAlunoMenuItemActionPerformed
        this.setContentPane((new PainelCadastroAluno(this)));
        setVisible(true);
    }//GEN-LAST:event_CadastroAlunoMenuItemActionPerformed

    private void CadastroProfessorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroProfessorMenuItemActionPerformed
        this.setContentPane(new PainelCadastroProfessor(this));
        setVisible(true);
    }//GEN-LAST:event_CadastroProfessorMenuItemActionPerformed

    private void CadastroAdministradorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroAdministradorMenuItemActionPerformed
        this.setContentPane(new PainelCadastroAdministrador(this));
        setVisible(true);
    }//GEN-LAST:event_CadastroAdministradorMenuItemActionPerformed

    private void jMenuItem38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem38ActionPerformed
        this.setContentPane(new ListarSalasPainel(this));
        this.setVisible(true);
    }//GEN-LAST:event_jMenuItem38ActionPerformed

    private void CadastroCursoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroCursoMenuItemActionPerformed
        this.setContentPane(new PainelCadastroCurso(this));
        setVisible(true);
    }//GEN-LAST:event_CadastroCursoMenuItemActionPerformed

    private void CadastroTurmaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroTurmaMenuItemActionPerformed
        this.setContentPane(new PainelCadastroTurma(this));
        setVisible(true);
    }//GEN-LAST:event_CadastroTurmaMenuItemActionPerformed

    private void CadastroDisciplinaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroDisciplinaMenuItemActionPerformed
        this.setContentPane(new PainelCadastroDisciplina(this));
        setVisible(true);
    }//GEN-LAST:event_CadastroDisciplinaMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        this.setContentPane(new PainelCadastroReposicaoDeAula(this));
        setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        this.setContentPane(new PainelCadastroHorarioAulasTurma(this));
        setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipalAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadastroAdministradorMenuItem;
    private javax.swing.JMenuItem CadastroAlunoMenuItem;
    private javax.swing.JMenuItem CadastroCursoMenuItem;
    private javax.swing.JMenuItem CadastroDisciplinaMenuItem;
    private javax.swing.JMenuItem CadastroProfessorMenuItem;
    private javax.swing.JMenuItem CadastroTurmaMenuItem;
    private javax.swing.JMenuItem ListarAdministradorMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem listarAlunoMenuItem;
    private javax.swing.JMenuItem listarCursoMenuItem;
    private javax.swing.JMenuItem listarDisciplinaMenuItem;
    private javax.swing.JMenuItem listarProfessorMenuItem;
    private javax.swing.JMenuItem listarTurmaMenuItem;
    // End of variables declaration//GEN-END:variables
}
