/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ifpb.dac.ga.desktop.ui;

import edu.ifpb.dac.ga.entidades.entidades.Professor;
import edu.ifpb.dac.service.ProfessorService;
import edu.ifpb.dac.service.locator.ServicesFacade;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcelo Augusto
 */
public class ListarProfesoresPainel extends javax.swing.JPanel {

    private FramePrincipalAdmin framePrincipal;
    private Professor professor;

    /**
     * Creates new form ListarAdministradoresPainel
     */
    public ListarProfesoresPainel() {
        initComponents();
    }

    public ListarProfesoresPainel(FramePrincipalAdmin framePrincipal) {
        this.framePrincipal = framePrincipal;
        initComponents();
        listarProfessoresNaTabela();
    }

    private void listarProfessoresNaTabela() {

        ProfessorService professorService = ServicesFacade.getProfessorService();
        List<Professor> professores = professorService.listarTodosProfessores();
        DefaultTableModel valor = (DefaultTableModel) tabela.getModel();
        for (Professor professor : professores) {
            valor.addRow(new Object[]{professor});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btEditar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setLayout(null);

        btEditar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/edit.png"))); // NOI18N
        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });
        add(btEditar);
        btEditar.setBounds(160, 440, 120, 40);

        btExcluir.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete_1.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        add(btExcluir);
        btExcluir.setBounds(340, 440, 120, 40);

        tabela.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Professores cadastrados"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tabela);
        tabela.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setResizable(false);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(160, 120, 480, 260);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel1.setText("Professores");
        add(jLabel1);
        jLabel1.setBounds(300, 20, 200, 50);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/block_1.png"))); // NOI18N
        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(520, 440, 110, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        DefaultTableModel valor = (DefaultTableModel) tabela.getModel();
        Professor professor = (Professor) valor.getValueAt(tabela.getSelectedRow(), 0);
        this.framePrincipal.setContentPane(new PainelEditarProfessor(framePrincipal, professor));
        this.framePrincipal.setVisible(true);
    }//GEN-LAST:event_btEditarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.framePrincipal.setContentPane(new PainelPrincipal());
        this.framePrincipal.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        DefaultTableModel valor = (DefaultTableModel) tabela.getModel();
        Professor teacher = (Professor) valor.getValueAt(tabela.getSelectedRow(), 0);
        ProfessorService professorService = ServicesFacade.getProfessorService();
        if (professorService.remover(teacher)) {
            JOptionPane.showMessageDialog(null, "Professor removido com sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "O professor não pode ser removido!");
        }

    }//GEN-LAST:event_btExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
