/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ifpb.dac.ga.desktop.ui;

import edu.ifpb.dac.ga.entidades.entidades.LocalEntity;
import edu.ifpb.dac.service.LocalService;
import edu.ifpb.dac.service.locator.ServicesFacade;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcelo Augusto
 */
public class ListarSalasPainel extends javax.swing.JPanel {
    private FramePrincipalAdmin framePrincipal;

    /**
     * Creates new form ListarAdministradoresPainel
     */
    public ListarSalasPainel() {
        initComponents();
    }
    public ListarSalasPainel(FramePrincipalAdmin framePrincipal){
        this.framePrincipal = framePrincipal;
        initComponents();
        listarLocaisNaTabela();
    }
    private void listarLocaisNaTabela() {
        LocalService localService = ServicesFacade.getLocalService();
        List<LocalEntity> locais = localService.listarTodosOsLocais();
        DefaultTableModel valor = (DefaultTableModel) tabela.getModel();
        for (LocalEntity local : locais) {
            valor.addRow(new Object[]{local.getDescricao()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setLayout(null);

        tabela.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição"
            }
        ));
        tabela.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tabela);
        tabela.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        add(jScrollPane1);
        jScrollPane1.setBounds(170, 120, 480, 260);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel1.setText("Locais");
        add(jLabel1);
        jLabel1.setBounds(350, 30, 100, 50);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/block_1.png"))); // NOI18N
        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(350, 430, 110, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.framePrincipal.setContentPane(new PainelPrincipal());
        this.framePrincipal.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
