/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ifpb.dac.ga.desktop.ui;

//import edu.ifpb.dac.ga.entidades.entidades.Aluno;
import edu.ifpb.dac.ga.entidades.entidades.Aluno;
import edu.ifpb.dac.ga.entidades.entidades.Curso;
import edu.ifpb.dac.service.AlunoService;
import edu.ifpb.dac.service.CursoService;
import edu.ifpb.dac.service.locator.ServicesFacade;
import edu.ifpb.dac.validator.Validador;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcelo Augusto
 */
public class PainelCadastroAluno extends javax.swing.JPanel {

    /**
     * Creates new form PainelCadastroAluno
     */
    private List<Curso> cursos;
    FramePrincipalAdmin framePrincipal;

    //private Aluno aluno;
    public PainelCadastroAluno() {
        initComponents();
        carregarComboBoxCurso();
    }

    public PainelCadastroAluno(FramePrincipalAdmin framePrincipal) {
        this.framePrincipal = framePrincipal;
        initComponents();
        carregarComboBoxCurso();
    }

    private void carregarComboBoxCurso() {
        CursoService cursoService = ServicesFacade.getCursoService();
        cursos = cursoService.listarTodosOsCursos();
        for (Curso curso : cursos) {
            cursoComboBox.addItem(curso);
        }
    }

//    public PainelCadastroAluno(FramePrincipalAdmin framePrincipal, Aluno aluno){
//        this.framePrincipal = framePrincipal;
//        initComponents();
//        this.aluno = aluno;
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoMatricula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoCPF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoRG = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        campoEmail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cursoComboBox = new javax.swing.JComboBox();

        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/image_edit.png"))); // NOI18N
        jLabel2.setText("Cadastro de aluno");
        add(jLabel2);
        jLabel2.setBounds(280, 40, 260, 50);

        campoNome.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        add(campoNome);
        campoNome.setBounds(220, 130, 420, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Nome Completo");
        add(jLabel5);
        jLabel5.setBounds(120, 130, 100, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("Matrícula");
        add(jLabel6);
        jLabel6.setBounds(150, 180, 60, 30);

        campoMatricula.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        campoMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoMatriculaActionPerformed(evt);
            }
        });
        add(campoMatricula);
        campoMatricula.setBounds(220, 180, 190, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Curso");
        add(jLabel4);
        jLabel4.setBounds(170, 240, 40, 30);

        campoCPF.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        add(campoCPF);
        campoCPF.setBounds(220, 290, 190, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("RG");
        add(jLabel3);
        jLabel3.setBounds(170, 340, 30, 30);

        campoRG.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        campoRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoRGActionPerformed(evt);
            }
        });
        add(campoRG);
        campoRG.setBounds(220, 340, 190, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("Email");
        add(jLabel1);
        jLabel1.setBounds(170, 390, 40, 30);

        campoEmail.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        campoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEmailActionPerformed(evt);
            }
        });
        add(campoEmail);
        campoEmail.setBounds(220, 390, 410, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/accept_1.png"))); // NOI18N
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(270, 470, 100, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete_1.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(430, 470, 110, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setText("CPF");
        add(jLabel7);
        jLabel7.setBounds(180, 290, 30, 30);

        add(cursoComboBox);
        cursoComboBox.setBounds(220, 240, 190, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void campoRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoRGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoRGActionPerformed

    private void campoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEmailActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Aluno aluno = new Aluno();
        aluno.setNome(campoNome.getText());
        aluno.setCpf(campoCPF.getText());
        aluno.setRg(campoRG.getText());
        aluno.setEmail(campoEmail.getText());
        aluno.setMatricula(campoMatricula.getText());
        aluno.setSenha(campoMatricula.getText());
        
        aluno.setCurso((Curso) cursoComboBox.getSelectedItem());
        Validador<Aluno> validador = new Validador();
        if (validador.ehValido(aluno)) {
            AlunoService alunoService = ServicesFacade.getAlunoService();
            alunoService.cadastrar(aluno);
            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
            campoCPF.setText("");
            campoEmail.setText("");
            campoMatricula.setText("");
            campoNome.setText("");
            campoRG.setText("");
        }else{
            JOptionPane.showMessageDialog(null, validador.getErros());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.framePrincipal.setContentPane(new PainelPrincipal());
        this.framePrincipal.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void campoMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoMatriculaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoCPF;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoMatricula;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoRG;
    private javax.swing.JComboBox cursoComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
