/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ifpb.dac.ga.desktop.ui;

import edu.ifpb.dac.ga.entidades.entidades.Aluno;
import edu.ifpb.dac.ga.entidades.entidades.Curso;
import edu.ifpb.dac.ga.entidades.entidades.Disciplina;
import edu.ifpb.dac.ga.entidades.entidades.Professor;
import edu.ifpb.dac.ga.entidades.entidades.Turma;
import edu.ifpb.dac.service.AlunoService;
import edu.ifpb.dac.service.CursoService;
import edu.ifpb.dac.service.DisciplinaService;
import edu.ifpb.dac.service.ProfessorService;
import edu.ifpb.dac.service.TurmaService;
import edu.ifpb.dac.service.locator.ServicesFacade;
import edu.ifpb.dac.validator.Validador;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcelo Augusto
 */
public class PainelEditarTurma extends javax.swing.JPanel {

    /**
     * Creates new form PainelCadastroTurma
     */
    private List<Curso> cursos;
    private List<Aluno> alunosTodos;
    private List<Disciplina> disciplinas;
    private List<Aluno> alunosTurma;
    private List<Professor> professores;
    FramePrincipalAdmin framePrincipal;
    Turma turma;

    public PainelEditarTurma() {
        initComponents();
    }

    public PainelEditarTurma(FramePrincipalAdmin framePrincipalAdmin, Turma turma) {
        this.turma = turma;
        this.framePrincipal = framePrincipalAdmin;
        initComponents();
        carregarComboBoxAlunos();
        carregarComboBoxCurso();
        carregarComboBoxProfessores();
        carregarComboBoxDisciplinas();
        campoIdentificacao.setText(turma.getIdentificacao());
        alunosTurma = turma.getAlunos();
        listarAlunosNaTabela();
    }

    private void listarAlunosNaTabela() {
        DefaultTableModel valor = (DefaultTableModel) tabelaAlunos.getModel();
        for (Aluno aluno : alunosTurma) {
            valor.addRow(new Object[]{aluno.getNome(), aluno.getMatricula()});
        }
    }

    private void carregarComboBoxCurso() {
        CursoService cursoService = ServicesFacade.getCursoService();
        cursos = cursoService.listarTodosOsCursos();
        for (Curso curso : cursos) {
            comboBoxCursos.addItem(curso);
        }
    }

    private void carregarComboBoxProfessores() {
        ProfessorService professorService = ServicesFacade.getProfessorService();
        professores = professorService.listarTodosProfessores();
        for (Professor professor : professores) {
            comboBoxProfessores.addItem(professor);
        }
    }

    private void carregarComboBoxAlunos() {
        AlunoService alunoService = ServicesFacade.getAlunoService();
        alunosTodos = alunoService.listarTodosAlunos();
        for (Aluno aluno : alunosTodos) {
            comboBoxAlunos.addItem(aluno);
        }
    }

    private void carregarComboBoxDisciplinas() {
        DisciplinaService disciplinaService = ServicesFacade.getDisciplinaService();
        disciplinas = disciplinaService.listarTodasDisciplinas();
        for (Disciplina disciplina : disciplinas) {
            comboBoxDisciplinas.addItem(disciplina);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoIdentificacao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        comboBoxAlunos = new javax.swing.JComboBox();
        comboBoxCursos = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        comboBoxProfessores = new javax.swing.JComboBox();
        btAddAluno = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAlunos = new javax.swing.JTable();
        comboBoxDisciplinas = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();

        setLayout(null);

        campoIdentificacao.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        campoIdentificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIdentificacaoActionPerformed(evt);
            }
        });
        add(campoIdentificacao);
        campoIdentificacao.setBounds(230, 110, 450, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("Identificação");
        add(jLabel1);
        jLabel1.setBounds(140, 110, 80, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Curso");
        add(jLabel2);
        jLabel2.setBounds(180, 160, 40, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Professor");
        add(jLabel3);
        jLabel3.setBounds(160, 260, 60, 30);

        btSalvar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/accept_1.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        add(btSalvar);
        btSalvar.setBounds(280, 540, 110, 30);

        btCancelar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete_1.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        add(btCancelar);
        btCancelar.setBounds(490, 540, 110, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/image_edit.png"))); // NOI18N
        jLabel4.setText("Editar Turma");
        add(jLabel4);
        jLabel4.setBounds(260, 30, 270, 40);

        add(comboBoxAlunos);
        comboBoxAlunos.setBounds(230, 310, 290, 30);

        add(comboBoxCursos);
        comboBoxCursos.setBounds(230, 160, 290, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Aluno");
        add(jLabel5);
        jLabel5.setBounds(180, 310, 40, 30);

        add(comboBoxProfessores);
        comboBoxProfessores.setBounds(230, 260, 290, 30);

        btAddAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add.png"))); // NOI18N
        btAddAluno.setText("Add aluno");
        btAddAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddAlunoActionPerformed(evt);
            }
        });
        add(btAddAluno);
        btAddAluno.setBounds(560, 310, 120, 30);

        tabelaAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Matrícula"
            }
        ));
        jScrollPane1.setViewportView(tabelaAlunos);

        add(jScrollPane1);
        jScrollPane1.setBounds(230, 370, 450, 140);

        add(comboBoxDisciplinas);
        comboBoxDisciplinas.setBounds(230, 210, 290, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("Disciplina");
        add(jLabel6);
        jLabel6.setBounds(160, 210, 60, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void campoIdentificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIdentificacaoActionPerformed

    }//GEN-LAST:event_campoIdentificacaoActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed

        turma.setDisciplina((Disciplina) comboBoxDisciplinas.getSelectedItem());
        turma.setProfessor((Professor) comboBoxProfessores.getSelectedItem());
        turma.setIdentificacao(campoIdentificacao.getText());
        //    turma.setAlunos(this.alunos);
        Validador<Turma> validador = new Validador();
        if (validador.ehValido(turma)) {
            TurmaService turmaService = ServicesFacade.getTurmaService();
            turmaService.atualizar(turma);
            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
            campoIdentificacao.setText("");
            DefaultTableModel valor = (DefaultTableModel) tabelaAlunos.getModel();
            this.framePrincipal.setContentPane(new PainelEditarTurma(this.framePrincipal, this.turma));
            this.framePrincipal.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, validador.getErros());
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.framePrincipal.setContentPane(new PainelPrincipal());
        this.framePrincipal.setVisible(true);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btAddAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddAlunoActionPerformed
        Aluno aluno = (Aluno) comboBoxAlunos.getSelectedItem();
        if (!alunosTurma.contains(aluno)) {
            alunosTurma.add(aluno);
            DefaultTableModel valor = (DefaultTableModel) tabelaAlunos.getModel();
            valor.addRow(new Object[]{aluno.getNome(), aluno.getMatricula()});
        } else {
            JOptionPane.showMessageDialog(null, "Aluno já cadastrado na turma!");
        }

    }//GEN-LAST:event_btAddAlunoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddAluno;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JTextField campoIdentificacao;
    private javax.swing.JComboBox comboBoxAlunos;
    private javax.swing.JComboBox comboBoxCursos;
    private javax.swing.JComboBox comboBoxDisciplinas;
    private javax.swing.JComboBox comboBoxProfessores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaAlunos;
    // End of variables declaration//GEN-END:variables
}
