/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ifpb.dac.ga.desktop.ui;

//import edu.ifpb.dac.ga.entidades.entidades.Disciplina;
import edu.ifpb.dac.ga.entidades.entidades.Curso;
import edu.ifpb.dac.ga.entidades.entidades.Disciplina;
import edu.ifpb.dac.service.CursoService;
import edu.ifpb.dac.service.DisciplinaService;
import edu.ifpb.dac.service.locator.ServicesFacade;
import edu.ifpb.dac.validator.Validador;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcelo Augusto
 */
public class PainelCadastroDisciplina extends javax.swing.JPanel {

    /**
     * Creates new form PainelCadastroDisciplina
     */
    private List<Curso> cursos;
    FramePrincipalAdmin framePrincipal;

    //private Disciplina disciplina;
    public PainelCadastroDisciplina() {
        initComponents();
    }

    public PainelCadastroDisciplina(FramePrincipalAdmin framePrincipal) {
        this.framePrincipal = framePrincipal;
        initComponents();
        carregarComboBoxCurso();
        carregarComboboxPeriodo();
    }

    private void carregarComboBoxCurso() {
        CursoService cursoService = ServicesFacade.getCursoService();
        cursos = cursoService.listarTodosOsCursos();
        for (Curso curso : cursos) {
            comboboxCurso.addItem(curso);
        }
    }

    private void carregarComboboxPeriodo() {
        for (int k = 1; k < 12; k++) {
            comboBoxPeriodos.addItem(k);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoDescricao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoAbreviacao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboBoxPeriodos = new javax.swing.JComboBox();
        campoCargaHoraria = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoAulasSemana = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        comboboxCurso = new javax.swing.JComboBox();

        setMinimumSize(new java.awt.Dimension(893, 535));
        setLayout(null);

        campoDescricao.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        campoDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDescricaoActionPerformed(evt);
            }
        });
        add(campoDescricao);
        campoDescricao.setBounds(270, 140, 410, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("Descrição");
        add(jLabel1);
        jLabel1.setBounds(200, 140, 60, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Abreviação");
        add(jLabel2);
        jLabel2.setBounds(190, 190, 70, 30);

        campoAbreviacao.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        add(campoAbreviacao);
        campoAbreviacao.setBounds(270, 190, 200, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Curso");
        add(jLabel3);
        jLabel3.setBounds(220, 240, 40, 30);

        btSalvar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/accept_1.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        add(btSalvar);
        btSalvar.setBounds(320, 460, 110, 30);

        btCancelar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete_1.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        add(btCancelar);
        btCancelar.setBounds(470, 460, 110, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/image_edit.png"))); // NOI18N
        jLabel4.setText("Cadastro de Disciplina");
        add(jLabel4);
        jLabel4.setBounds(320, 30, 300, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Período");
        add(jLabel5);
        jLabel5.setBounds(210, 290, 50, 30);

        add(comboBoxPeriodos);
        comboBoxPeriodos.setBounds(270, 290, 200, 30);

        campoCargaHoraria.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        add(campoCargaHoraria);
        campoCargaHoraria.setBounds(270, 340, 200, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("Carga horária");
        add(jLabel6);
        jLabel6.setBounds(180, 340, 80, 30);

        campoAulasSemana.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        add(campoAulasSemana);
        campoAulasSemana.setBounds(270, 390, 200, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setText("Aulas por semana");
        add(jLabel7);
        jLabel7.setBounds(150, 390, 110, 30);

        add(comboboxCurso);
        comboboxCurso.setBounds(270, 240, 200, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void campoDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDescricaoActionPerformed

    }//GEN-LAST:event_campoDescricaoActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        Disciplina disciplina = new Disciplina();
        disciplina.setDescricao(campoDescricao.getText());
        disciplina.setAbreviacao(campoAbreviacao.getText());
        disciplina.setCurso((Curso) comboboxCurso.getSelectedItem());
        disciplina.setPeriodo((int)comboBoxPeriodos.getSelectedItem());
        try {
            int cargaHoraria2 = Integer.parseInt(campoCargaHoraria.getText());
            disciplina.setCargaHoraria(cargaHoraria2);
            int aulasSemana2 = Integer.parseInt(campoAulasSemana.getText());
            disciplina.setAulasSemana(aulasSemana2);
            Validador<Disciplina> validador = new Validador();
            if (validador.ehValido(disciplina)) {
                DisciplinaService disciplinaService = ServicesFacade.getDisciplinaService();
                disciplinaService.cadastrar(disciplina);
                JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
                campoAbreviacao.setText("");
                campoAulasSemana.setText("");
                campoCargaHoraria.setText("");
                campoDescricao.setText("");
            } else {
                JOptionPane.showMessageDialog(null, validador.getErros());
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "O campo Carga horária e Aulas por semana deve receber apenas números!");
            campoCargaHoraria.setText("");
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.framePrincipal.setContentPane(new PainelPrincipal());
        this.framePrincipal.setVisible(true);
    }//GEN-LAST:event_btCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JTextField campoAbreviacao;
    private javax.swing.JTextField campoAulasSemana;
    private javax.swing.JTextField campoCargaHoraria;
    private javax.swing.JTextField campoDescricao;
    private javax.swing.JComboBox comboBoxPeriodos;
    private javax.swing.JComboBox comboboxCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
