/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ifpb.dac.ga.desktop.ui;

//import edu.ifpb.dac.ga.entidades.entidades.Curso;
import edu.ifpb.dac.ga.entidades.entidades.Curso;
import edu.ifpb.dac.service.CursoService;
import edu.ifpb.dac.service.locator.ServicesFacade;
import edu.ifpb.dac.validator.Validador;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcelo Augusto
 */
public class PainelEditarCurso extends javax.swing.JPanel {

    /**
     * Creates new form PainelCadastroCurso
     */
    FramePrincipalAdmin framePrincipal;
    private Curso curso;

    //private Curso curso;
    public PainelEditarCurso() {
        initComponents();
    }

    public PainelEditarCurso(FramePrincipalAdmin framePrincipalAdmin, Curso curso) {
        this.framePrincipal = framePrincipalAdmin;
        initComponents();
        this.curso = curso;
        campoAbreviacao1.setText(curso.getAbreviacao());
        campoDescricao.setText(curso.getDescricao());
        campoPeriodos.setText(curso.getPeriodos()+"");
        campoUnidade.setText(curso.getUnidade());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        campoDescricao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoPeriodos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoUnidade = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        campoAbreviacao1 = new javax.swing.JTextField();

        setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/image_edit.png"))); // NOI18N
        jLabel4.setText("Cadastro de Curso");
        add(jLabel4);
        jLabel4.setBounds(330, 60, 260, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("Descrição");
        add(jLabel1);
        jLabel1.setBounds(200, 140, 60, 30);

        campoDescricao.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        campoDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDescricaoActionPerformed(evt);
            }
        });
        add(campoDescricao);
        campoDescricao.setBounds(270, 140, 410, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Abreviação");
        add(jLabel2);
        jLabel2.setBounds(190, 190, 70, 30);

        campoPeriodos.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        campoPeriodos.setToolTipText("Este campo deve receber apenas números");
        campoPeriodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPeriodosActionPerformed(evt);
            }
        });
        add(campoPeriodos);
        campoPeriodos.setBounds(270, 240, 200, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Qtd de períodos");
        add(jLabel5);
        jLabel5.setBounds(160, 240, 100, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("Unidade");
        add(jLabel6);
        jLabel6.setBounds(200, 290, 60, 30);

        campoUnidade.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        add(campoUnidade);
        campoUnidade.setBounds(270, 290, 200, 30);

        btSalvar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/accept_1.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        add(btSalvar);
        btSalvar.setBounds(320, 400, 110, 30);

        btCancelar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete_1.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        add(btCancelar);
        btCancelar.setBounds(470, 400, 110, 30);

        campoAbreviacao1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        campoAbreviacao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoAbreviacao1ActionPerformed(evt);
            }
        });
        add(campoAbreviacao1);
        campoAbreviacao1.setBounds(270, 190, 200, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.framePrincipal.setContentPane(new PainelPrincipal());
        this.framePrincipal.setVisible(true);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        curso.setDescricao(campoDescricao.getText());
        curso.setAbreviacao(campoAbreviacao1.getText());
        curso.setUnidade(campoUnidade.getText());
        String qtdePeriodos = campoPeriodos.getText();        
        try {
            int qtdePeriodosInt = Integer.parseInt(qtdePeriodos);
            curso.setPeriodos(qtdePeriodosInt);
            Validador<Curso> validador = new Validador();
            if (validador.ehValido(curso)) {
                CursoService cursoService = ServicesFacade.getCursoService();
                cursoService.atualizar(curso);
                JOptionPane.showMessageDialog(null, "Atualização realizada com Sucesso!");
            } else {
                JOptionPane.showMessageDialog(null, validador.getErros());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "O campo quantidade de períodos deve receber apenas números!");
            campoPeriodos.setText("");
        }

    }//GEN-LAST:event_btSalvarActionPerformed

    private void campoDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDescricaoActionPerformed

    }//GEN-LAST:event_campoDescricaoActionPerformed

    private void campoPeriodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPeriodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPeriodosActionPerformed

    private void campoAbreviacao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAbreviacao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoAbreviacao1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JTextField campoAbreviacao1;
    private javax.swing.JTextField campoDescricao;
    private javax.swing.JTextField campoPeriodos;
    private javax.swing.JTextField campoUnidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
