/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ifpb.dac.ga.desktop.ui;

//import edu.ifpb.dac.ga.entidades.entidades.Administrador;
import edu.ifpb.dac.ga.entidades.entidades.Administrador;
import edu.ifpb.dac.service.AdministradorService;
import edu.ifpb.dac.service.locator.ServicesFacade;
import edu.ifpb.dac.validator.Validador;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcelo Augusto
 */
public class PainelEditarAdministrador extends javax.swing.JPanel {

    /**
     * Creates new form PainelCadastroAdministrador
     */
    FramePrincipalAdmin framePrincipal;
    private Administrador administrador;

    //private Administrador administrador;
    public PainelEditarAdministrador() {
        initComponents();
    }

    public PainelEditarAdministrador(FramePrincipalAdmin frame, Administrador adm) {
        this.framePrincipal = frame;
        initComponents();
        this.administrador = adm;
        this.campoNome.setText(adm.getNome());
        this.campoLogin.setText(adm.getLogin());
        this.campoSenha.setText(adm.getLogin());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoLogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        campoSenha = new javax.swing.JPasswordField();

        setLayout(null);

        campoNome.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        campoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeActionPerformed(evt);
            }
        });
        add(campoNome);
        campoNome.setBounds(190, 180, 410, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("Nome completo");
        add(jLabel1);
        jLabel1.setBounds(90, 180, 90, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Login");
        add(jLabel2);
        jLabel2.setBounds(150, 230, 30, 30);

        campoLogin.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        add(campoLogin);
        campoLogin.setBounds(190, 230, 200, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Senha");
        add(jLabel3);
        jLabel3.setBounds(140, 280, 40, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/accept_1.png"))); // NOI18N
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(210, 360, 110, 30);

        botaoCancelar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        botaoCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete_1.png"))); // NOI18N
        botaoCancelar.setText("Sair");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });
        add(botaoCancelar);
        botaoCancelar.setBounds(350, 360, 110, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/image_edit.png"))); // NOI18N
        jLabel4.setText("Cadastro de Administrador");
        add(jLabel4);
        jLabel4.setBounds(160, 70, 350, 40);

        campoSenha.setText("jPasswordField1");
        add(campoSenha);
        campoSenha.setBounds(190, 280, 200, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeActionPerformed


    }//GEN-LAST:event_campoNomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        this.administrador.setNome(campoNome.getText());
        this.administrador.setLogin(campoLogin.getText());
        this.administrador.setSenha(new String(campoSenha.getPassword()));

        Validador<Administrador> validador = new Validador<>();

        if (validador.ehValido(this.administrador)) {
            AdministradorService administradorSevice = ServicesFacade.getAdministradorService();
            administradorSevice.atualizar(this.administrador);
            JOptionPane.showMessageDialog(null, "Cadastro atualizado com Sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, validador.getErros());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        this.framePrincipal.setContentPane(new PainelPrincipal());
        this.framePrincipal.setVisible(true);
    }//GEN-LAST:event_botaoCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JTextField campoLogin;
    private javax.swing.JTextField campoNome;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
